{{cookiecutter.app_name}}/app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login


class User(UserMixin, db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True, nullable=False)
    email = db.Column(db.String(120), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    token = db.Column(db.String(64), index=True, unique=True)
    token_expiration = db.Column(db.DateTime)


    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(id)

{{cookiecutter.app_name}}/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from settings import Config


db = SQLAlchemy()
bootstrap = Bootstrap()
login = LoginManager()
login.login_view = 'auth.login'
toolbar = DebugToolbarExtension()


def create_app(config_object=Config):
    app = Flask(__name__)
    app.config.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)

    return app


def register_extensions(app):
    db.init_app(app)
    bootstrap.init_app(app)
    login.init_app(app)
    toolbar.init_app(app)


def register_blueprints(app):
    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.dashboard import bp as dash_bp
    app.register_blueprint(dash_bp)

    from app.errors import bp as err_bp
    app.register_blueprint(err_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

{{cookiecutter.app_name}}/app/dashboard/__init__.py
from flask import Blueprint


bp = Blueprint('dashboard', __name__,  url_prefix='/dashboard')

from app.dashboard import routes

{{cookiecutter.app_name}}/app/dashboard/routes.py
from flask import render_template
from flask_login import login_required
from app.dashboard import bp


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    return render_template('dashboard/index.html')

{{cookiecutter.app_name}}/app/main/__init__.py
from flask import Blueprint


bp = Blueprint('main', __name__)

from app.main import routes

{{cookiecutter.app_name}}/app/main/routes.py
from flask import render_template
from flask_login import login_required
from app.main import bp


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html', title='{{ cookiecutter.app_name|title }}')

{{cookiecutter.app_name}}/app/templates/base.html
{% raw %}
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">{% endraw %}{{ cookiecutter.app_name|title }}{% raw %}</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('dashboard.index') }}">Dashboard</a></li>
                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/app/templates/dashboard/index.html
{% raw %}
{% extends "base.html" %}

{% block app_content %}
    <h1 class="text-center">Dashboard</h1>
{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/app/templates/index.html
{% raw %}
{% extends "base.html" %}

{% block app_content %}
    <h1 class="text-center">{{ title }}</h1>
{% endblock %}
{% endraw %}